#!/usr/bin/env bash

# Print true if Bluetooth adapter is present and powered on
if [[ $(systemctl is-active bluetooth 2>/dev/null || true) != "active" ]]; then
  echo false
  exit 0
fi

if bluetoothctl show | grep -q "Powered: yes"; then
  echo true
else
  echo false
fi
