#!/bin/bash

length="$(playerctl metadata mpris:length 2>/dev/null || echo 0)"

if [[ -z "$length" ]] || ! [[ "$length" =~ ^[0-9]+$ ]]; then
  echo 0
  exit 0
fi

if (( length <= 0 )); then
  echo 0
  exit 0
fi

awk -v value="$length" 'BEGIN { printf "%d\n", value / 1000000 }'
