# Cyberpunk Theme for Kitty

foreground #e0e0e0
background #0b0c15
selection_foreground #000000
selection_background #ff0055

# Cursor
cursor #00ff99
cursor_text_color #000000

# URL
url_color #00ff99

# Black
color0 #121212
color8 #2d2d2d

# Red
color1 #ff2a6d
color9 #ff5e7d

# Green
color2 #05ffa6
color10 #5af78e

# Yellow
color3 #f5e65b
color11 #fffc58

# Blue
color4 #00f0ff
color12 #5ccfe6

# Magenta
color5 #bd00ff
color13 #ff0099

# Cyan
color6 #01ffc3
color14 #5ef1ff

# White
color7 #dcdcdc
color1 #ffffff
