# Doom One Theme for Kitty

foreground #bbc2cf
background #282c34
selection_foreground #bbc2cf
selection_background #3e4451

# Cursor
cursor #51afef
cursor_text_color #282c34

# URL
url_color #46d9ff

# Black
color0 #1c1f24
color8 #5b6268

# Red
color1 #ff6c6b
color9 #da8548

# Green
color2 #98be65
color10 #4db5bd

# Yellow
color3 #ecbe7b
color11 #ecbe7b

# Blue
color4 #51afef
color12 #3071db

# Magenta
color5 #c678dd
color13 #a9a1e1

# Cyan
color6 #46d9ff
color14 #46d9ff

# White
color7 #bfc6d4
color15 #dfdfdf
