# --- Font Configuration ---
font_family      JetBrainsMono Nerd Font
font_size        14.0

# --- Window Layout ---
remember_window_size  no
initial_width         960
initial_height        600
window_padding_width  4
shell fish
# --- Color Scheme & Opacity ---
include theme.conf

# --- Performance & Bell ---
enable_audio_bell no
update_check_interval 0
cursor_shape underline
shell_integration no-cursor
opacity 1
