import QtQuick

QtObject {
    // Auto-generated by theme-chooser — Theme: Eldritch
    readonly property string gradientTop: "#212337"
    readonly property string gradientMid: "#292b40"
    readonly property string gradientBottom: "#1d2032"
    readonly property string border: "#7081d0"
    readonly property string borderDim: "#323449"
    readonly property string accent: "#37f499"
    readonly property int accentR: 55
    readonly property int accentG: 244
    readonly property int accentB: 153
    readonly property string text: "#ebfafa"
    readonly property string textMuted: "#7081d0"
    readonly property string textDim: "#535d8f"
    readonly property string cardBg: "#292b40"
    readonly property string darkBase: "#171928"
    readonly property string red: "#f16c75"
    readonly property string green: "#37f499"
    readonly property string orange: "#f1fc79"
    readonly property string purple: "#a48cf2"
    readonly property string yellow: "#f1fc79"
    readonly property string cyan: "#04d1f9"
    readonly property string pink: "#f265b5"
}
