import QtQuick

QtObject {
    // Auto-generated by theme-chooser — Theme: Amber
    readonly property string gradientTop: "#e60c0c0c"
    readonly property string gradientMid: "#e6131313"
    readonly property string gradientBottom: "#e60f0f0f"
    readonly property string border: "#6b5636"
    readonly property string borderDim: "#2a1c0e"
    readonly property string accent: "#ffb454"
    readonly property int accentR: 255
    readonly property int accentG: 180
    readonly property int accentB: 84
    readonly property string text: "#f5ead8"
    readonly property string textMuted: "#a08a63"
    readonly property string textDim: "#6b5636"
    readonly property string cardBg: "#e6131313"
    readonly property string darkBase: "#0a0a0a"
    readonly property string red: "#ff5f4d"
    readonly property string green: "#9fbf6e"
    readonly property string orange: "#ffd27a"
    readonly property string purple: "#c98a5e"
    readonly property string yellow: "#ffd27a"
    readonly property string cyan: "#4fa8a0"
    readonly property string pink: "#ff6a3d"
}
