import QtQuick

QtObject {
    // Auto-generated by theme-chooser — Theme: Gruvbox
    readonly property string gradientTop: "#282828"
    readonly property string gradientMid: "#3c3836"
    readonly property string gradientBottom: "#504945"
    readonly property string border: "#504945"
    readonly property string borderDim: "#3c3836"
    readonly property string accent: "#fabd2f"
    readonly property int accentR: 250
    readonly property int accentG: 189
    readonly property int accentB: 47
    readonly property string text: "#ebdbb2"
    readonly property string textMuted: "#928374"
    readonly property string textDim: "#7c6f64"
    readonly property string cardBg: "#3c3836"
    readonly property string darkBase: "#282828"
    readonly property string red: "#fb4934"
    readonly property string green: "#b8bb26"
    readonly property string orange: "#fabd2f"
    readonly property string purple: "#d3869b"
    readonly property string yellow: "#fabd2f"
    readonly property string cyan: "#83a598"
    readonly property string pink: "#fb4934"
}
