# Fuzzel config, amber / ember / translucent vibes (matches waybar's Amber Sunset)

[main]
font=JetBrainsMono Nerd Font:size=15
dpi-aware=auto
icon-theme=Kanagawa
icons-enabled=yes
terminal=alacritty
prompt="❯   "
placeholder=Search apps…
match-mode=fuzzy
sort-result=yes
lines=10
width=45
horizontal-pad=28
vertical-pad=30
inner-pad=14
letter-spacing=1
use-bold=yes

[colors]
background=0a0a0ae6
text=f5ead8ff
prompt=ffb454ff
placeholder=a08a63aa
input=f5ead8ff
match=ffb454ff
selection=131313e6
selection-text=ffffffff
selection-match=ff6a3dff
border=ffb454ff
counter=a08a63ff
[border]
width=2
radius=0
