# Messages (ie: shutdown)

msg_color               #c0caf5
msg_font                Sofia Pro:size=18:bold:dpi=120
msg_x                   1695
msg_y                   325

# Session Name

session_color           #c0caf5
session_font            Sofia Pro:size=16:bold:dpi=120
session_x               1695
session_y               995

# valid values: stretch, tile

background_style        tile
background_color        #1a1b26

# Input controls (centered input panel)

input_panel_x           15%
input_panel_y           50%

# Offsets for name and password input boxes (adjust these if necessary)
input_name_x            175
input_name_y            407
input_pass_x            175
input_pass_y            494
input_font              Sofia Pro:size=16:dpi=96:style=Bold
input_color             #1a1b26

username_msg            "Username:"
password_msg            "Password:"

