[global]
frame_color = "#69d2b4"
separator_color = auto

[urgency_low]
foreground = "#e9f5ee"
background = "#101612"

[urgency_normal]
foreground = "#e9f5ee"
background = "#101612"

[urgency_critical]
foreground = "#e9f5ee"
background = "#101612"
