# Obtém os preenchimentos automáticos do editor com base em um esquema de configuração
"$schema" = 'https://starship.rs/config-schema.json'

# Insere uma quebra de linha entre os prompts do shell
add_newline = true

# Substitui o símbolo "❯" no prompt por "➜"
[character] # O nome do módulo que estamos configurando é "character"
success_symbol = "[❯](bold green)" # O segmento "success_symbol" está sendo definido como "➜" com a cor verde em negrito

# Desativa o módulo do pacote, ocultando-o completamente do prompt
[package]
disabled = true
