[colors.primary]
background = "#0b0c15"
foreground = "#e0e0e0"

[colors.cursor]
text = "#000000"
cursor = "#00ff99"

[colors.selection]
text = "#000000"
background = "#ff0055"

[colors.normal]
black = "#121212"
blue = "#00f0ff"
cyan = "#01ffc3"
green = "#05ffa6"
magenta = "#bd00ff"
red = "#ff2a6d"
white = "#dcdcdc"
yellow = "#f5e65b"

[colors.bright]
black = "#2d2d2d"
blue = "#5ccfe6"
cyan = "#5ef1ff"
green = "#5af78e"
magenta = "#ff0099"
red = "#ff5e7d"
white = "#ffffff"
yellow = "#fffc58"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "underline"

[env]
TERM = "alacritty"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 1000
multiplier = 3

[terminal.shell]
program = "/bin/fish"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.85
startup_mode = "Windowed"
title = "Alacritty"

[window.padding]
x = 10
y = 10

[terminal]
